// Generated by feishu-plugin-platform action generator. Human-auditable.
// Title: 写回多维表格记录
import { basekit, Component } from '@lark-opdev/block-basekit-server-api';

// 出网域名白名单(只能调用一次)
basekit.addDomainList(['open.feishu.cn']);

basekit.addAction({
  formItems: [
    { itemId: 'appId', label: '应用 App ID', required: true, component: Component.Input },
    { itemId: 'appSecret', label: '应用 App Secret', required: true, component: Component.Input },
    { itemId: 'appToken', label: '目标多维表格 app_token', required: true, component: Component.Input },
    { itemId: 'tableId', label: '目标数据表 table_id', required: true, component: Component.Input },
    { itemId: 'title', label: '标题内容', required: true, component: Component.Input },
    { itemId: 'content', label: '正文内容', required: true, component: Component.Input },
  ],
  execute: async (args: Record<string, any>, context) => {
    function debugLog(arg: any) {
      console.log(JSON.stringify({ arg }), '\n');
    }
    const fetch = async (url: string, init?: any): Promise<any> => {
      const r = await context.fetch(url, init);
      const text = await r.text();
      return JSON.parse(text);
    };
    try {
      const s_token: any = await fetch(`https://open.feishu.cn/open-apis/auth/v3/tenant_access_token/internal`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ "app_id": `${args.appId}`, "app_secret": `${args.appSecret}` }) });
      const s_create: any = await fetch(`https://open.feishu.cn/open-apis/bitable/v1/apps/${args.appToken}/tables/${args.tableId}/records/batch_create`, { method: 'POST', headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${s_token?.tenant_access_token}` }, body: JSON.stringify({ "records": [{ "fields": { "标题": `${args.title}`, "正文": `${args.content}` } }] }) });
      const res: any = s_create;
      return {
        code: res?.code,
        record_id: res?.data?.records?.[0]?.record_id,
      };
    } catch (e) {
      debugLog({ '===error': String(e) });
      return {};
    }
  },
  resultType: {
    type: 'object',
    properties: {
      code: { label: '返回码(0为成功)', type: 'number' },
      record_id: { label: '新记录ID', type: 'string' },
    },
  },
});
export default basekit;
