// Generated by feishu-plugin-platform action generator. Human-auditable.
// Title: 人民币兑美元换算
import { basekit, Component } from '@lark-opdev/block-basekit-server-api';

// 出网域名白名单(只能调用一次)
basekit.addDomainList(['api.exchangerate-api.com']);

basekit.addAction({
  formItems: [
    { itemId: 'amount', label: '人民币金额', required: true, component: Component.Input },
  ],
  execute: async (args: Record<string, any>, context) => {
    function debugLog(arg: any) {
      console.log(JSON.stringify({ arg }), '\n');
    }
    const fetch = async (url: string, init?: any): Promise<any> => {
      const r = await context.fetch(url, init);
      const text = await r.text();
      return JSON.parse(text);
    };
    try {
      const res: any = await fetch(`https://api.exchangerate-api.com/v4/latest/CNY`, { method: 'GET' });
      return {
        usd_amount: args.amount * res?.rates?.USD,
        exchange_rate: res?.rates?.USD,
      };
    } catch (e) {
      debugLog({ '===error': String(e) });
      return {};
    }
  },
  resultType: {
    type: 'object',
    properties: {
      usd_amount: { label: '美元金额', type: 'number' },
      exchange_rate: { label: '汇率', type: 'number' },
    },
  },
});
export default basekit;
