package shortcut

import (
	"archive/zip"
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// Pinned to the versions validated end-to-end on 2026-06-22 (testField hit a
// real external API and wrote back correctly).
const (
	serverAPIVersion = "1.0.6"
	cliVersion       = "1.0.5"
	resultIcon       = "https://lf3-static.bytednsdoc.com/obj/eden-cn/eqgeh7upeubqnulog/chatbot.svg"
)

// jsStr renders a Go string as a single-quoted JS string literal.
func jsStr(s string) string {
	r := strings.NewReplacer(`\`, `\\`, `'`, `\'`, "\n", `\n`, "\r", `\r`)
	return "'" + r.Replace(s) + "'"
}

// renderBodyValue lowers a POST body value to JS: "{key}" → inp.key (input
// injection), otherwise a quoted string literal.
func renderBodyValue(v string) string {
	if ref := bodyRef(v); ref != "" {
		return "inp." + ref
	}
	return jsStr(v)
}

// renderPropValue lowers a result property's value to JS: a template renders as
// a JS template literal (`...${inp.key}...`); otherwise the expression is translated.
func renderPropValue(p ResultProp) string {
	if strings.TrimSpace(p.Template) != "" {
		return "`" + renderURLTemplate(p.Template) + "`"
	}
	return translateExpr(p.Expr)
}

// tsType maps a FieldType enum name to the TS type of an input param.
func tsType(fieldType string) string {
	switch fieldType {
	case "Number":
		return "number"
	case "Text":
		return "string"
	case "Checkbox":
		return "boolean"
	default:
		return "any"
	}
}

// localeValue returns the label for a locale, falling back to zh_CN so t() never
// renders an empty string in en/ja.
func localeValue(l I18n, locale string) string {
	switch locale {
	case "en-US":
		if l.EnUS != "" {
			return l.EnUS
		}
	case "ja-JP":
		if l.JaJP != "" {
			return l.JaJP
		}
	}
	return l.ZhCN
}

// RenderIndexTS compiles the DSL into the basekit src/index.ts source. The
// output is intended to be human-readable and auditable.
func RenderIndexTS(f FieldShortcut) (string, error) {
	if err := f.Validate(); err != nil {
		return "", err
	}

	// Collect i18n keys: form item labels + result property labels (non-empty).
	type kv struct{ key string; label I18n }
	var labels []kv
	for _, it := range f.FormItems {
		labels = append(labels, kv{it.Key, it.Label})
	}
	for _, p := range f.Result.Properties {
		if !p.Label.empty() {
			labels = append(labels, kv{p.Key, p.Label})
		}
	}

	var b strings.Builder
	w := func(format string, a ...any) { fmt.Fprintf(&b, format, a...) }

	w("// Generated by feishu-plugin-platform shortcut generator. Human-auditable.\n")
	w("// Title: %s\n", f.Title.ZhCN)
	w("import { basekit, FieldType, field, FieldComponent, FieldCode, NumberFormatter, AuthorizationType } from '@lark-opdev/block-basekit-server-api';\n")
	w("const { t } = field;\n\n")

	// Domain allowlist — only needed when the shortcut makes an outbound request.
	if len(f.Domains) > 0 {
		quoted := make([]string, len(f.Domains))
		for i, d := range f.Domains {
			quoted[i] = jsStr(d)
		}
		w("// 出网域名白名单(只能调用一次,多次会互相覆盖)\n")
		w("basekit.addDomainList([%s]);\n\n", strings.Join(quoted, ", "))
	}

	w("basekit.addField({\n")

	// authorizations — credential the user supplies at config time (never hardcoded).
	if f.Auth != nil {
		a := f.Auth
		w("  authorizations: [\n    {\n")
		w("      id: %s,\n", jsStr(a.ID))
		w("      type: AuthorizationType.%s,\n", a.Type)
		w("      label: %s,\n", jsStr(a.Label))
		w("      platform: %s,\n", jsStr(a.Platform))
		w("      required: true,\n")
		w("      instructionsUrl: %s,\n", jsStr(a.InstructionsURL))
		switch a.Type {
		case "QueryParamToken":
			w("      params: { paramName: %s },\n", jsStr(a.ParamName))
		case "CustomHeaderToken":
			w("      params: { headerName: %s },\n", jsStr(a.ParamName))
		}
		w("      icon: { light: %s, dark: %s },\n", jsStr(resultIcon), jsStr(resultIcon))
		w("    },\n  ],\n")
	}

	// i18n
	w("  i18n: {\n    messages: {\n")
	for _, locale := range []string{"zh-CN", "en-US", "ja-JP"} {
		w("      '%s': {\n", locale)
		for _, l := range labels {
			w("        %s: %s,\n", jsStr(l.key), jsStr(localeValue(l.label, locale)))
		}
		w("      },\n")
	}
	w("    },\n  },\n")

	// formItems
	w("  formItems: [\n")
	for _, it := range f.FormItems {
		w("    {\n")
		w("      key: %s,\n", jsStr(it.Key))
		w("      label: t(%s),\n", jsStr(it.Key))
		w("      component: FieldComponent.%s,\n", it.Component)
		if len(it.SupportType) > 0 {
			sts := make([]string, len(it.SupportType))
			for i, st := range it.SupportType {
				sts[i] = "FieldType." + st
			}
			w("      props: { supportType: [%s] },\n", strings.Join(sts, ", "))
		}
		w("      validator: { required: %t },\n", it.Required)
		w("    },\n")
	}
	w("  ],\n")

	// resultType (Object)
	w("  resultType: {\n    type: FieldType.Object,\n    extra: {\n")
	w("      icon: { light: %s },\n", jsStr(resultIcon))
	w("      properties: [\n")
	for _, p := range f.Result.Properties {
		w("        {\n")
		w("          key: %s,\n", jsStr(p.Key))
		w("          type: FieldType.%s,\n", p.Type)
		if p.Label.empty() {
			w("          label: %s,\n", jsStr(p.Key))
		} else {
			w("          label: t(%s),\n", jsStr(p.Key))
		}
		if p.Primary {
			w("          primary: true,\n")
		}
		if p.Hidden {
			w("          hidden: true,\n")
		}
		if p.GroupByKey {
			w("          isGroupByKey: true,\n")
		}
		if p.Formatter != "" {
			w("          extra: { formatter: NumberFormatter.%s },\n", p.Formatter)
		}
		w("        },\n")
	}
	w("      ],\n    },\n  },\n")

	// execute
	paramType := make([]string, len(f.FormItems))
	for i, it := range f.FormItems {
		paramType[i] = fmt.Sprintf("%s: %s", it.Key, tsType(it.SupportType0()))
	}
	w("  execute: async (formItemParams: { %s }, context) => {\n", strings.Join(paramType, "; "))
	w("    const inp: Record<string, any> = formItemParams;\n")
	// Pre-render output values, then emit only the expression helpers they use.
	propVals := make([]string, len(f.Result.Properties))
	for i, p := range f.Result.Properties {
		propVals[i] = renderPropValue(p)
	}
	emitExprHelpers(&b, "    ", propVals)
	b.WriteString(executeHelpers)
	w("    try {\n")
	if strings.TrimSpace(f.Execute.URL) != "" {
		// Fetch mode: build the init object (method + optional JSON body) + optional authId.
		init := fmt.Sprintf("{ method: %s }", jsStr(f.Execute.Method))
		if len(f.Execute.Body) > 0 {
			bodyKeys := make([]string, 0, len(f.Execute.Body))
			for k := range f.Execute.Body {
				bodyKeys = append(bodyKeys, k)
			}
			sort.Strings(bodyKeys)
			parts := make([]string, len(bodyKeys))
			for i, k := range bodyKeys {
				parts[i] = fmt.Sprintf("%s: %s", k, renderBodyValue(f.Execute.Body[k]))
			}
			init = fmt.Sprintf("{ method: %s, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ %s }) }",
				jsStr(f.Execute.Method), strings.Join(parts, ", "))
		}
		authArg := ""
		if f.Auth != nil {
			authArg = ", " + jsStr(f.Auth.ID) // basekit runtime injects the user's credential
		}
		w("      const res: any = await fetch(`%s`, %s%s);\n", renderURLTemplate(f.Execute.URL), init, authArg)
	}
	// else: compute-only — no outbound request; outputs come from inputs/templates.
	w("      return {\n        code: FieldCode.Success,\n        data: {\n")
	for i, p := range f.Result.Properties {
		w("          %s: %s,\n", p.Key, propVals[i])
	}
	w("        },\n      };\n")
	w("    } catch (e) {\n")
	w("      debugLog({ '===error': String(e) });\n")
	w("      return { code: FieldCode.Error };\n")
	w("    }\n")
	w("  },\n")

	w("});\nexport default basekit;\n")
	return b.String(), nil
}

// SupportType0 returns the first supportType (for typing the input param), or "".
func (it FormItem) SupportType0() string {
	if len(it.SupportType) > 0 {
		return it.SupportType[0]
	}
	return ""
}

// executeHelpers are the proven debugLog + fetch wrapper from the official demo,
// kept verbatim so generated shortcuts log and error-handle the canonical way.
const executeHelpers = `    function debugLog(arg: any) {
      console.log(JSON.stringify({ arg, logID: context.logID }), '\n');
    }
    debugLog('=====start=====');
    const fetch = async (url: string, init?: any, authId?: any): Promise<any> => {
      try {
        const r = await context.fetch(url, init, authId);
        const text = await r.text();
        debugLog({ ['===fetch ' + url]: text.slice(0, 4000) });
        return JSON.parse(text);
      } catch (e) {
        debugLog({ ['===fetch error ' + url]: String(e) });
        return { code: -1, error: e };
      }
    };
`

// sampleValue returns a test input value literal for a form item type.
func sampleValue(fieldType string) string {
	switch fieldType {
	case "Number":
		return "100"
	case "Checkbox":
		return "true"
	default:
		return `"test"`
	}
}

// RenderTestTS produces test/index.ts that runs testField with sample inputs.
func RenderTestTS(f FieldShortcut) string {
	var args []string
	for _, it := range f.FormItems {
		args = append(args, fmt.Sprintf("        %s: %s,", it.Key, sampleValue(it.SupportType0())))
	}
	return fmt.Sprintf(`import { testField, createFieldContext } from "@lark-opdev/block-basekit-server-api";

async function run() {
    const context = await createFieldContext();
    testField({
%s
    }, context);
}

run();
`, strings.Join(args, "\n"))
}

// RenderPackageJSON produces package.json for the generated project.
func RenderPackageJSON(f FieldShortcut) string {
	return fmt.Sprintf(`{
  "name": %s,
  "version": "1.0.0",
  "description": %s,
  "main": "index.js",
  "scripts": {
    "start": "block-basekit-cli start:field",
    "build": "block-basekit-cli build:field",
    "pack": "block-basekit-cli pack:field"
  },
  "license": "ISC",
  "devDependencies": {
    "@lark-opdev/block-basekit-cli": "%s"
  },
  "dependencies": {
    "@lark-opdev/block-basekit-server-api": "%s"
  }
}
`, jsonStr(f.ID), jsonStr(f.Title.ZhCN), cliVersion, serverAPIVersion)
}

// jsonStr renders a Go string as a double-quoted JSON string literal.
func jsonStr(s string) string {
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`, "\n", `\n`, "\r", `\r`, "\t", `\t`)
	return `"` + r.Replace(s) + `"`
}

const tsconfigJSON = `{
  "compilerOptions": {
    "target": "ES2020",
    "rootDir": "src",
    "moduleResolution": "node",
    "module": "commonjs",
    "declaration": false,
    "inlineSourceMap": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "skipLibCheck": true,
    "lib": ["ES2020"],
    "allowJs": true,
    "checkJs": true
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules/**"]
}
`

// Files renders the full, buildable basekit project for f as an in-memory
// map of relative-path → content. Scaffold and Zip both build on this so disk
// and archive output never drift.
func Files(f FieldShortcut) (map[string]string, error) {
	index, err := RenderIndexTS(f)
	if err != nil {
		return nil, err
	}
	return map[string]string{
		"package.json":  RenderPackageJSON(f),
		"tsconfig.json": tsconfigJSON,
		"config.json":   "{\n  \"authorizations\": []\n}\n",
		"src/index.ts":  index,
		"test/index.ts": RenderTestTS(f),
		"README.md": fmt.Sprintf("# %s\n\nGenerated field shortcut (basekit), human-auditable source.\n\n"+
			"## Build & upload\n\n```\nnpm install\nnpm run build   # type-check\nnpm run pack    # -> output/*.zip\n```\n\n"+
			"Then upload the zip to your Feishu developer console (field-shortcut capability) and have an admin approve it.\n", f.Title.ZhCN),
	}, nil
}

// sortedKeys returns the file paths in deterministic order.
func sortedKeys(files map[string]string) []string {
	keys := make([]string, 0, len(files))
	for k := range files {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// Scaffold writes a full, buildable basekit project for f under dir.
func Scaffold(f FieldShortcut, dir string) error {
	files, err := Files(f)
	if err != nil {
		return err
	}
	for _, rel := range sortedKeys(files) {
		p := filepath.Join(dir, rel)
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(p, []byte(files[rel]), 0o644); err != nil {
			return err
		}
	}
	return nil
}

// Zip renders the project and returns it as a .zip archive (the downloadable
// deliverable for the web platform).
func Zip(f FieldShortcut) ([]byte, error) {
	files, err := Files(f)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	zw := zip.NewWriter(&buf)
	for _, rel := range sortedKeys(files) {
		fw, err := zw.Create(rel)
		if err != nil {
			return nil, err
		}
		if _, err := fw.Write([]byte(files[rel])); err != nil {
			return nil, err
		}
	}
	if err := zw.Close(); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
