// Generated by feishu-plugin-platform shortcut generator. Human-auditable.
// Title: 文本转大写
import { basekit, FieldType, field, FieldComponent, FieldCode, NumberFormatter, AuthorizationType } from '@lark-opdev/block-basekit-server-api';
const { t } = field;

basekit.addField({
  i18n: {
    messages: {
      'zh-CN': {
        'text': '文本字段',
        'upper_text': '大写文本',
      },
      'en-US': {
        'text': 'Text Field',
        'upper_text': 'Uppercase Text',
      },
      'ja-JP': {
        'text': 'テキストフィールド',
        'upper_text': '大文字テキスト',
      },
    },
  },
  formItems: [
    {
      key: 'text',
      label: t('text'),
      component: FieldComponent.FieldSelect,
      props: { supportType: [FieldType.Text] },
      validator: { required: true },
    },
  ],
  resultType: {
    type: FieldType.Object,
    extra: {
      icon: { light: 'https://lf3-static.bytednsdoc.com/obj/eden-cn/eqgeh7upeubqnulog/chatbot.svg' },
      properties: [
        {
          key: 'upper_text',
          type: FieldType.Text,
          label: t('upper_text'),
          primary: true,
        },
        {
          key: '_id',
          type: FieldType.Text,
          label: '_id',
          hidden: true,
          isGroupByKey: true,
        },
      ],
    },
  },
  execute: async (formItemParams: { text: string }, context) => {
    const inp: Record<string, any> = formItemParams;
    const _upper = (s: any) => String(s).toUpperCase();
    function debugLog(arg: any) {
      console.log(JSON.stringify({ arg, logID: context.logID }), '\n');
    }
    debugLog('=====start=====');
    const fetch = async (url: string, init?: any, authId?: any): Promise<any> => {
      try {
        const r = await context.fetch(url, init, authId);
        const text = await r.text();
        debugLog({ ['===fetch ' + url]: text.slice(0, 4000) });
        return JSON.parse(text);
      } catch (e) {
        debugLog({ ['===fetch error ' + url]: String(e) });
        return { code: -1, error: e };
      }
    };
    try {
      return {
        code: FieldCode.Success,
        data: {
          upper_text: _upper(inp.text),
          _id: String(Math.random()),
        },
      };
    } catch (e) {
      debugLog({ '===error': String(e) });
      return { code: FieldCode.Error };
    }
  },
});
export default basekit;
