// Generated by feishu-plugin-platform shortcut generator. Human-auditable.
// Title: 人民币→美元汇率换算
import { basekit, FieldType, field, FieldComponent, FieldCode, NumberFormatter, AuthorizationType } from '@lark-opdev/block-basekit-server-api';
const { t } = field;

// 出网域名白名单(只能调用一次,多次会互相覆盖)
basekit.addDomainList(['api.exchangerate-api.com']);

basekit.addField({
  i18n: {
    messages: {
      'zh-CN': {
        'amount': '人民币金额',
        '_id': '行ID',
        'usd_amount': '美元金额',
        'rate': '当前汇率',
      },
      'en-US': {
        'amount': 'Amount (CNY)',
        '_id': 'Row ID',
        'usd_amount': 'USD Amount',
        'rate': 'Exchange Rate',
      },
      'ja-JP': {
        'amount': '人民元金額',
        '_id': '行ID',
        'usd_amount': '米ドル金額',
        'rate': '為替レート',
      },
    },
  },
  formItems: [
    {
      key: 'amount',
      label: t('amount'),
      component: FieldComponent.FieldSelect,
      props: { supportType: [FieldType.Number] },
      validator: { required: true },
    },
  ],
  resultType: {
    type: FieldType.Object,
    extra: {
      icon: { light: 'https://lf3-static.bytednsdoc.com/obj/eden-cn/eqgeh7upeubqnulog/chatbot.svg' },
      properties: [
        {
          key: '_id',
          type: FieldType.Text,
          label: t('_id'),
          hidden: true,
          isGroupByKey: true,
        },
        {
          key: 'usd_amount',
          type: FieldType.Number,
          label: t('usd_amount'),
          primary: true,
          extra: { formatter: NumberFormatter.DIGITAL_ROUNDED_2 },
        },
        {
          key: 'rate',
          type: FieldType.Number,
          label: t('rate'),
          extra: { formatter: NumberFormatter.DIGITAL_ROUNDED_4 },
        },
      ],
    },
  },
  execute: async (formItemParams: { amount: number }, context) => {
    const inp: Record<string, any> = formItemParams;
    function debugLog(arg: any) {
      console.log(JSON.stringify({ arg, logID: context.logID }), '\n');
    }
    debugLog('=====start=====');
    const fetch = async (url: string, init?: any, authId?: any): Promise<any> => {
      try {
        const r = await context.fetch(url, init, authId);
        const text = await r.text();
        debugLog({ ['===fetch ' + url]: text.slice(0, 4000) });
        return JSON.parse(text);
      } catch (e) {
        debugLog({ ['===fetch error ' + url]: String(e) });
        return { code: -1, error: e };
      }
    };
    try {
      const res: any = await fetch(`https://api.exchangerate-api.com/v4/latest/CNY`, { method: 'GET' });
      return {
        code: FieldCode.Success,
        data: {
          _id: String(Math.random()),
          usd_amount: inp.amount * res?.rates?.USD,
          rate: res?.rates?.USD,
        },
      };
    } catch (e) {
      debugLog({ '===error': String(e) });
      return { code: FieldCode.Error };
    }
  },
});
export default basekit;
