// Generated by feishu-plugin-platform shortcut generator. Human-auditable.
// Title: 姓名拼接
import { basekit, FieldType, field, FieldComponent, FieldCode, NumberFormatter, AuthorizationType } from '@lark-opdev/block-basekit-server-api';
const { t } = field;

basekit.addField({
  i18n: {
    messages: {
      'zh-CN': {
        'firstName': '姓',
        'lastName': '名',
        'fullName': '全名',
      },
      'en-US': {
        'firstName': 'Last Name',
        'lastName': 'First Name',
        'fullName': 'Full Name',
      },
      'ja-JP': {
        'firstName': '姓',
        'lastName': '名',
        'fullName': 'フルネーム',
      },
    },
  },
  formItems: [
    {
      key: 'firstName',
      label: t('firstName'),
      component: FieldComponent.Input,
      validator: { required: true },
    },
    {
      key: 'lastName',
      label: t('lastName'),
      component: FieldComponent.Input,
      validator: { required: true },
    },
  ],
  resultType: {
    type: FieldType.Object,
    extra: {
      icon: { light: 'https://lf3-static.bytednsdoc.com/obj/eden-cn/eqgeh7upeubqnulog/chatbot.svg' },
      properties: [
        {
          key: 'fullName',
          type: FieldType.Text,
          label: t('fullName'),
          primary: true,
        },
        {
          key: '_rowId',
          type: FieldType.Text,
          label: '_rowId',
          hidden: true,
          isGroupByKey: true,
        },
      ],
    },
  },
  execute: async (formItemParams: { firstName: any; lastName: any }, context) => {
    const inp: Record<string, any> = formItemParams;
    function debugLog(arg: any) {
      console.log(JSON.stringify({ arg, logID: context.logID }), '\n');
    }
    debugLog('=====start=====');
    const fetch = async (url: string, init?: any, authId?: any): Promise<any> => {
      try {
        const r = await context.fetch(url, init, authId);
        const text = await r.text();
        debugLog({ ['===fetch ' + url]: text.slice(0, 4000) });
        return JSON.parse(text);
      } catch (e) {
        debugLog({ ['===fetch error ' + url]: String(e) });
        return { code: -1, error: e };
      }
    };
    try {
      return {
        code: FieldCode.Success,
        data: {
          fullName: `${inp.firstName}${inp.lastName}`,
          _rowId: String(Math.random()),
        },
      };
    } catch (e) {
      debugLog({ '===error': String(e) });
      return { code: FieldCode.Error };
    }
  },
});
export default basekit;
