// Generated by feishu-plugin-platform shortcut generator. Human-auditable.
// Title: GitHub 主页链接
import { basekit, FieldType, field, FieldComponent, FieldCode, NumberFormatter, AuthorizationType } from '@lark-opdev/block-basekit-server-api';
const { t } = field;

basekit.addField({
  i18n: {
    messages: {
      'zh-CN': {
        'username': 'GitHub 用户名',
        'username_out': '用户名',
        'homepage': '主页(可点击)',
      },
      'en-US': {
        'username': 'GitHub Username',
        'username_out': '用户名',
        'homepage': '主页(可点击)',
      },
      'ja-JP': {
        'username': 'GitHub 用户名',
        'username_out': '用户名',
        'homepage': '主页(可点击)',
      },
    },
  },
  formItems: [
    {
      key: 'username',
      label: t('username'),
      component: FieldComponent.FieldSelect,
      props: { supportType: [FieldType.Text] },
      validator: { required: true },
    },
  ],
  resultType: {
    type: FieldType.Object,
    extra: {
      icon: { light: 'https://lf3-static.bytednsdoc.com/obj/eden-cn/eqgeh7upeubqnulog/chatbot.svg' },
      properties: [
        {
          key: 'username_out',
          type: FieldType.Text,
          label: t('username_out'),
          primary: true,
        },
        {
          key: 'homepage',
          type: FieldType.Url,
          label: t('homepage'),
        },
        {
          key: '_id',
          type: FieldType.Text,
          label: '_id',
          hidden: true,
          isGroupByKey: true,
        },
      ],
    },
  },
  execute: async (formItemParams: { username: string }, context) => {
    const inp: Record<string, any> = formItemParams;
    function debugLog(arg: any) {
      console.log(JSON.stringify({ arg, logID: context.logID }), '\n');
    }
    debugLog('=====start=====');
    const fetch = async (url: string, init?: any, authId?: any): Promise<any> => {
      try {
        const r = await context.fetch(url, init, authId);
        const text = await r.text();
        debugLog({ ['===fetch ' + url]: text.slice(0, 4000) });
        return JSON.parse(text);
      } catch (e) {
        debugLog({ ['===fetch error ' + url]: String(e) });
        return { code: -1, error: e };
      }
    };
    try {
      return {
        code: FieldCode.Success,
        data: {
          username_out: inp.username,
          homepage: { text: `https://github.com/${inp.username}`, link: `https://github.com/${inp.username}` },
          _id: String(Math.random()),
        },
      };
    } catch (e) {
      debugLog({ '===error': String(e) });
      return { code: FieldCode.Error };
    }
  },
});
export default basekit;
