// Generated by feishu-plugin-platform shortcut generator. Human-auditable.
// Title: 标签拆分多选
import { basekit, FieldType, field, FieldComponent, FieldCode, NumberFormatter, AuthorizationType } from '@lark-opdev/block-basekit-server-api';
const { t } = field;

basekit.addField({
  i18n: {
    messages: {
      'zh-CN': {
        'raw': '逗号分隔标签',
        'first': '原文',
        'tags': '标签',
      },
      'en-US': {
        'raw': '逗号分隔标签',
        'first': '原文',
        'tags': '标签',
      },
      'ja-JP': {
        'raw': '逗号分隔标签',
        'first': '原文',
        'tags': '标签',
      },
    },
  },
  formItems: [
    {
      key: 'raw',
      label: t('raw'),
      component: FieldComponent.FieldSelect,
      props: { supportType: [FieldType.Text] },
      validator: { required: true },
    },
  ],
  resultType: {
    type: FieldType.Object,
    extra: {
      icon: { light: 'https://lf3-static.bytednsdoc.com/obj/eden-cn/eqgeh7upeubqnulog/chatbot.svg' },
      properties: [
        {
          key: 'first',
          type: FieldType.Text,
          label: t('first'),
          primary: true,
        },
        {
          key: 'tags',
          type: FieldType.MultiSelect,
          label: t('tags'),
        },
        {
          key: '_id',
          type: FieldType.Text,
          label: '_id',
          hidden: true,
          isGroupByKey: true,
        },
      ],
    },
  },
  execute: async (formItemParams: { raw: string }, context) => {
    const inp: Record<string, any> = formItemParams;
    const _trim = (s: any): any => String(s).trim();
    const _split = (s: any, d: any): any => String(s).split(String(d)).map((x: any) => x.trim()).filter(Boolean);
    function debugLog(arg: any) {
      console.log(JSON.stringify({ arg, logID: context.logID }), '\n');
    }
    debugLog('=====start=====');
    const fetch = async (url: string, init?: any, authId?: any): Promise<any> => {
      try {
        const r = await context.fetch(url, init, authId);
        const text = await r.text();
        debugLog({ ['===fetch ' + url]: text.slice(0, 4000) });
        return JSON.parse(text);
      } catch (e) {
        debugLog({ ['===fetch error ' + url]: String(e) });
        return { code: -1, error: e };
      }
    };
    try {
      return {
        code: FieldCode.Success,
        data: {
          first: _trim(inp.raw),
          tags: _split(inp.raw, ','),
          _id: String(Math.random()),
        },
      };
    } catch (e) {
      debugLog({ '===error': String(e) });
      return { code: FieldCode.Error };
    }
  },
});
export default basekit;
