// Generated by feishu-plugin-platform shortcut generator. Human-auditable.
// Title: IP地理位置查询
import { basekit, FieldType, field, FieldComponent, FieldCode, NumberFormatter, AuthorizationType } from '@lark-opdev/block-basekit-server-api';
const { t } = field;

// 出网域名白名单(只能调用一次,多次会互相覆盖)
basekit.addDomainList(['ip-api.com']);

basekit.addField({
  i18n: {
    messages: {
      'zh-CN': {
        'ip': 'IP地址',
        'country': '国家',
        'city': '城市',
        'isp': '运营商',
        '_id': 'ID',
      },
      'en-US': {
        'ip': 'IP Address',
        'country': 'Country',
        'city': 'City',
        'isp': 'ISP',
        '_id': 'ID',
      },
      'ja-JP': {
        'ip': 'IPアドレス',
        'country': '国',
        'city': '都市',
        'isp': 'ISP',
        '_id': 'ID',
      },
    },
  },
  formItems: [
    {
      key: 'ip',
      label: t('ip'),
      component: FieldComponent.FieldSelect,
      props: { supportType: [FieldType.Text] },
      validator: { required: true },
    },
  ],
  resultType: {
    type: FieldType.Object,
    extra: {
      icon: { light: 'https://lf3-static.bytednsdoc.com/obj/eden-cn/eqgeh7upeubqnulog/chatbot.svg' },
      properties: [
        {
          key: 'country',
          type: FieldType.Text,
          label: t('country'),
          primary: true,
        },
        {
          key: 'city',
          type: FieldType.Text,
          label: t('city'),
        },
        {
          key: 'isp',
          type: FieldType.Text,
          label: t('isp'),
        },
        {
          key: '_id',
          type: FieldType.Text,
          label: t('_id'),
          hidden: true,
          isGroupByKey: true,
        },
      ],
    },
  },
  execute: async (formItemParams: { ip: string }, context) => {
    const inp: Record<string, any> = formItemParams;
    function debugLog(arg: any) {
      console.log(JSON.stringify({ arg, logID: context.logID }), '\n');
    }
    debugLog('=====start=====');
    const fetch = async (url: string, init?: any, authId?: any): Promise<any> => {
      try {
        const r = await context.fetch(url, init, authId);
        const text = await r.text();
        debugLog({ ['===fetch ' + url]: text.slice(0, 4000) });
        return JSON.parse(text);
      } catch (e) {
        debugLog({ ['===fetch error ' + url]: String(e) });
        return { code: -1, error: e };
      }
    };
    try {
      const res: any = await fetch(`http://ip-api.com/json/${inp.ip}`, { method: 'GET' });
      return {
        code: FieldCode.Success,
        data: {
          country: res?.country,
          city: res?.city,
          isp: res?.isp,
          _id: String(Math.random()),
        },
      };
    } catch (e) {
      debugLog({ '===error': String(e) });
      return { code: FieldCode.Error };
    }
  },
});
export default basekit;
