// Generated by feishu-plugin-platform shortcut generator. Human-auditable.
// Title: 英文→中文翻译
import { basekit, FieldType, field, FieldComponent, FieldCode, NumberFormatter, AuthorizationType } from '@lark-opdev/block-basekit-server-api';
const { t } = field;

// 出网域名白名单(只能调用一次,多次会互相覆盖)
basekit.addDomainList(['api.mymemory.translated.net']);

basekit.addField({
  i18n: {
    messages: {
      'zh-CN': {
        'text': '待翻译文本',
        'translated_text': '译文',
      },
      'en-US': {
        'text': 'Text to translate',
        'translated_text': 'Translation',
      },
      'ja-JP': {
        'text': '翻訳するテキスト',
        'translated_text': '翻訳文',
      },
    },
  },
  formItems: [
    {
      key: 'text',
      label: t('text'),
      component: FieldComponent.FieldSelect,
      props: { supportType: [FieldType.Text] },
      validator: { required: true },
    },
  ],
  resultType: {
    type: FieldType.Object,
    extra: {
      icon: { light: 'https://lf3-static.bytednsdoc.com/obj/eden-cn/eqgeh7upeubqnulog/chatbot.svg' },
      properties: [
        {
          key: 'translated_text',
          type: FieldType.Text,
          label: t('translated_text'),
          primary: true,
        },
        {
          key: '_id',
          type: FieldType.Text,
          label: '_id',
          hidden: true,
          isGroupByKey: true,
        },
      ],
    },
  },
  execute: async (formItemParams: { text: string }, context) => {
    const inp: Record<string, any> = formItemParams;
    function debugLog(arg: any) {
      console.log(JSON.stringify({ arg, logID: context.logID }), '\n');
    }
    debugLog('=====start=====');
    const fetch = async (url: string, init?: any, authId?: any): Promise<any> => {
      try {
        const r = await context.fetch(url, init, authId);
        const text = await r.text();
        debugLog({ ['===fetch ' + url]: text.slice(0, 4000) });
        return JSON.parse(text);
      } catch (e) {
        debugLog({ ['===fetch error ' + url]: String(e) });
        return { code: -1, error: e };
      }
    };
    try {
      const res: any = await fetch(`https://api.mymemory.translated.net/get?q=${inp.text}&langpair=en|zh`, { method: 'GET' });
      return {
        code: FieldCode.Success,
        data: {
          translated_text: res?.responseData?.translatedText,
          _id: String(Math.random()),
        },
      };
    } catch (e) {
      debugLog({ '===error': String(e) });
      return { code: FieldCode.Error };
    }
  },
});
export default basekit;
