// Generated by feishu-plugin-platform shortcut generator. Human-auditable.
// Title: DeepSeek 文本润色
import { basekit, FieldType, field, FieldComponent, FieldCode, NumberFormatter, AuthorizationType } from '@lark-opdev/block-basekit-server-api';
const { t } = field;

// 出网域名白名单(只能调用一次,多次会互相覆盖)
basekit.addDomainList(['api.deepseek.com']);

basekit.addField({
  authorizations: [
    {
      id: 'apiKey',
      type: AuthorizationType.HeaderBearerToken,
      label: 'DeepSeek API Key',
      platform: 'DeepSeek',
      required: true,
      instructionsUrl: 'https://platform.deepseek.com/api_keys',
      icon: { light: 'https://lf3-static.bytednsdoc.com/obj/eden-cn/eqgeh7upeubqnulog/chatbot.svg', dark: 'https://lf3-static.bytednsdoc.com/obj/eden-cn/eqgeh7upeubqnulog/chatbot.svg' },
    },
  ],
  i18n: {
    messages: {
      'zh-CN': {
        'text': '待润色文本',
        'polished': '润色结果',
      },
      'en-US': {
        'text': 'Text to Polish',
        'polished': 'Polished Text',
      },
      'ja-JP': {
        'text': 'リライトするテキスト',
        'polished': 'リライト結果',
      },
    },
  },
  formItems: [
    {
      key: 'text',
      label: t('text'),
      component: FieldComponent.FieldSelect,
      props: { supportType: [FieldType.Text] },
      validator: { required: true },
    },
  ],
  resultType: {
    type: FieldType.Object,
    extra: {
      icon: { light: 'https://lf3-static.bytednsdoc.com/obj/eden-cn/eqgeh7upeubqnulog/chatbot.svg' },
      properties: [
        {
          key: 'polished',
          type: FieldType.Text,
          label: t('polished'),
          primary: true,
        },
        {
          key: '_id',
          type: FieldType.Text,
          label: '_id',
          hidden: true,
          isGroupByKey: true,
        },
      ],
    },
  },
  execute: async (formItemParams: { text: string }, context) => {
    const inp: Record<string, any> = formItemParams;
    function debugLog(arg: any) {
      console.log(JSON.stringify({ arg, logID: context.logID }), '\n');
    }
    debugLog('=====start=====');
    const fetch = async (url: string, init?: any, authId?: any): Promise<any> => {
      try {
        const r = await context.fetch(url, init, authId);
        const text = await r.text();
        debugLog({ ['===fetch ' + url]: text.slice(0, 4000) });
        return JSON.parse(text);
      } catch (e) {
        debugLog({ ['===fetch error ' + url]: String(e) });
        return { code: -1, error: e };
      }
    };
    try {
      const res: any = await fetch(`https://api.deepseek.com/chat/completions`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ "messages": [{ "content": `${inp.text}`, "role": "user" }], "model": "deepseek-chat" }) }, 'apiKey');
      return {
        code: FieldCode.Success,
        data: {
          polished: res?.choices?.[0]?.message?.content,
          _id: String(Math.random()),
        },
      };
    } catch (e) {
      debugLog({ '===error': String(e) });
      return { code: FieldCode.Error };
    }
  },
});
export default basekit;
