// Generated by feishu-plugin-platform shortcut generator. Human-auditable.
// Title: 身份证识别性别
import { basekit, FieldType, field, FieldComponent, FieldCode, NumberFormatter, AuthorizationType } from '@lark-opdev/block-basekit-server-api';
const { t } = field;

basekit.addField({
  i18n: {
    messages: {
      'zh-CN': {
        'idcard': '身份证号',
        'gender': '性别',
      },
      'en-US': {
        'idcard': 'ID Number',
        'gender': 'Gender',
      },
      'ja-JP': {
        'idcard': '身份证号',
        'gender': '性别',
      },
    },
  },
  formItems: [
    {
      key: 'idcard',
      label: t('idcard'),
      component: FieldComponent.FieldSelect,
      props: { supportType: [FieldType.Text] },
      validator: { required: true },
    },
  ],
  resultType: {
    type: FieldType.Object,
    extra: {
      icon: { light: 'https://lf3-static.bytednsdoc.com/obj/eden-cn/eqgeh7upeubqnulog/chatbot.svg' },
      properties: [
        {
          key: 'gender',
          type: FieldType.Text,
          label: t('gender'),
          primary: true,
        },
        {
          key: '_id',
          type: FieldType.Text,
          label: '_id',
          hidden: true,
          isGroupByKey: true,
        },
      ],
    },
  },
  execute: async (formItemParams: { idcard: string }, context) => {
    const inp: Record<string, any> = formItemParams;
    const _substr = (s: any, a: any, l: any): any => String(s).slice(Number(a), Number(a) + Number(l));
    const _eq = (a: any, b: any): any => String(a) === String(b);
    const _if = (c: any, a: any, b: any): any => (c ? a : b);
    function debugLog(arg: any) {
      console.log(JSON.stringify({ arg, logID: context.logID }), '\n');
    }
    debugLog('=====start=====');
    const fetch = async (url: string, init?: any, authId?: any): Promise<any> => {
      try {
        const r = await context.fetch(url, init, authId);
        const text = await r.text();
        debugLog({ ['===fetch ' + url]: text.slice(0, 4000) });
        return JSON.parse(text);
      } catch (e) {
        debugLog({ ['===fetch error ' + url]: String(e) });
        return { code: -1, error: e };
      }
    };
    try {
      return {
        code: FieldCode.Success,
        data: {
          gender: _if(_eq(_substr(inp.idcard, 16, 1) % 2, 1), '男', '女'),
          _id: String(Math.random()),
        },
      };
    } catch (e) {
      debugLog({ '===error': String(e) });
      return { code: FieldCode.Error };
    }
  },
});
export default basekit;
